Add kitten bee recipe
AllTheMods/atm6-sky pull request #463
Opened 2021-06-18 18:08 UTC by kts325

2021-06-18 19:28 UTC, DAmNRelentless requested changes
I highly recommend not saving the beds in a tuple.
Write a function for the recipe instead and apply an array of beds to it.

2021-06-18 22:07 UTC, kts325 commented
Uhh this is the way I was told to do it lol soooo

2021-06-19 18:18 UTC, ladylexxie approved these changes

2021-06-19 18:40 UTC, DAmNRelentless approved these changes

2021-06-19 19:59 UTC, merged